[server]
hosts = localhost:5232

[auth]
type = htpasswd
htpasswd_filename = ./radicale.htpasswd
htpasswd_encryption = plain

[storage]
filesystem_folder = ./radicale-collections

[rights]
type = owner_only
