/* guru_pool.c -- GENERATED by tools/gen_guru_pool.py. DO NOT EDIT.
 *
 * Source: firmware/main/guru_pool.txt -- edit that, then run
 * `make -C sim gurupool`. CI regenerates this file and diffs it, so a
 * hand edit here is a build failure rather than a quiet divergence.
 *
 * This is the pool the firmware falls back on. /sdcard/guru.txt, when
 * present, overrides it at runtime -- see gurupool.c. */
#include "guru.h"

const GuruTask GU_POOL_BUILTIN[] = {
 /* --- gut ----------------------------------------------------------------- */
 {  1, GU_CAT_GUT,    "One brazil nut",
      "A single nut is the whole ritual. More is not better here." },
 {  2, GU_CAT_GUT,    "Black garlic",
      "Garlic aged until it is sweet and soft. Eaten as-is, a clove at a time." },
 {  3, GU_CAT_GUT,    "Broccoli or sprouts",
      "The sprouts are the concentrated version of the same plant." },
 {  4, GU_CAT_GUT,    "Natto or another ferment",
      "Fermented soybeans. Kimchi, sauerkraut or miso count for this one." },
 {  5, GU_CAT_GUT,    "Kefir or live yoghurt",
      "Live cultures rather than the sweetened, pasteurised sort." },
 {  6, GU_CAT_GUT,    "A plant you have not had",
      "Variety is the point -- people who track this aim at thirty a week." },
 {  7, GU_CAT_GUT,    "Twelve hours between meals",
      "An overnight gap. Dinner early or breakfast late, whichever you prefer." },
 /* --- metabolic ----------------------------------------------------------- */
 {  8, GU_CAT_METAB,  "Zone 2, with a 140 burst",
      "Steady enough to hold a conversation, with one hard push in it." },
 {  9, GU_CAT_METAB,  "Twelve-second sprints",
      "All-out and very short, with a long walk back between each one." },
 { 10, GU_CAT_METAB,  "Walk after the big meal",
      "Ten minutes on your feet rather than sitting straight down." },
 { 11, GU_CAT_METAB,  "Sardines or mackerel",
      "Small oily fish. Tinned counts, and is what most people actually eat." },
 { 12, GU_CAT_METAB,  "Mineral water, glass bottle",
      "Volcanic if you can get it; glass because plastic is the part people mind." },
 { 13, GU_CAT_METAB,  "Protein before bed",
      "A small savoury something rather than a sweet one." },
 { 14, GU_CAT_METAB,  "Creatine",
      "The most boring and most studied supplement on the shelf." },
 /* --- mind ---------------------------------------------------------------- */
 { 15, GU_CAT_COGN,   "Morning sunlight, outdoors",
      "Outside, without glasses or a window in the way. Early is the point." },
 { 16, GU_CAT_COGN,   "A slow breath cycle",
      "Longer out than in, until the hurry goes out of it." },
 { 17, GU_CAT_COGN,   "Ten minutes of stillness",
      "Sitting, doing nothing, not listening to anything. Harder than it sounds." },
 { 18, GU_CAT_COGN,   "Learn something by heart",
      "A few lines, a phone number, a route. Recall is the exercise." },
 { 19, GU_CAT_COGN,   "Read on paper",
      "Long-form and un-scrollable, for as long as it holds you." },
 { 20, GU_CAT_COGN,   "A real conversation",
      "Voice or face, not typing. Length matters less than attention." },
 { 21, GU_CAT_COGN,   "Screens off before bed",
      "An hour of dimmer, duller things first." },
 /* --- strength ------------------------------------------------------------ */
 { 22, GU_CAT_STRUCT, "One set to real failure",
      "A single movement taken until the next rep will not happen." },
 { 23, GU_CAT_STRUCT, "Hang from a bar",
      "Dead weight, shoulders loose, for as long as your grip lasts." },
 { 24, GU_CAT_STRUCT, "Sit in a deep squat",
      "Heels down, all the way at the bottom. Rest there." },
 { 25, GU_CAT_STRUCT, "Calf raises to burning",
      "Slow, off a step, until they complain." },
 { 26, GU_CAT_STRUCT, "Grip work",
      "Carry something heavy until you have to put it down." },
 { 27, GU_CAT_STRUCT, "Hip and hamstring stretch",
      "The two that shorten from sitting. Held, not bounced." },
 { 28, GU_CAT_STRUCT, "Stand on one leg, eyes shut",
      "Balance is the one that quietly goes. Both legs, near a wall." },
 /* --- recovery ------------------------------------------------------------ */
 { 29, GU_CAT_RECOV,  "Woke at your usual time",
      "The same hour as yesterday, weekend included." },
 { 30, GU_CAT_RECOV,  "Cold finish to the shower",
      "The last stretch on cold, long enough to change your breathing." },
 { 31, GU_CAT_RECOV,  "Sauna or a long hot bath",
      "Heat, until you have properly had enough of it." },
 { 32, GU_CAT_RECOV,  "No caffeine after noon",
      "It is still working at bedtime whether you feel it or not." },
 { 33, GU_CAT_RECOV,  "Bedroom cold and dark",
      "Colder than feels reasonable, and dark enough to lose your hand." },
 { 34, GU_CAT_RECOV,  "A day without alcohol",
      "Simply a day that did not have any in it." },
 { 35, GU_CAT_RECOV,  "Nose-breathe overnight",
      "Mouth shut. People who chase this tape it; you do not have to." },
};

const int GU_POOL_BUILTIN_N = (int)(sizeof(GU_POOL_BUILTIN) / sizeof(GU_POOL_BUILTIN[0]));
