/* study_demo.h -- the demo course, built into the firmware (study_demo.c is
 * generated by tools/gen_study_demo.py from courses/demo-kanji/course.srs).
 * Const, so it lives in flash; Study copies it to the card on first run. */
#ifndef STUDY_DEMO_H
#define STUDY_DEMO_H
#include <stdint.h>

extern const uint32_t study_demo_size;
extern const uint32_t study_demo_fingerprint;
extern const uint8_t study_demo_srs[];

#endif
