#!/usr/bin/env python3
"""The reading font: kana at 20 px, drawn from the course pictures' font.

Study's cards list an item's readings (on'yomi, kun'yomi) in a line of text.
The 38 px lv_font_kana is the Kana trainer's, sized for one character on a
screen of its own, and at that size two readings fill a line. This is the
same kana at 20 px, drawn from the pinned Noto Sans JP that tools/mkcourse.py
draws the kanji pictures with (the same font file and Pillow version), so a
reading sits beside its kanji in one face. The 1-bit threshold is lower than
the pictures' (72, not 128): at 20 px a kana's strokes are about a pixel and
a half wide, and at 128 they break up.

Ranges: the ideographic comma and full stop (to separate readings), hiragana
and katakana, as lv_font_kana has them. Anything else in a reading (a Latin
letter, a hyphen) falls back to the Palm font.

  python3 tools/gen_kana_font.py          write firmware/main/lv_font_kana_20.c
  python3 tools/gen_kana_font.py --check  exit 1 if the file isn't what this writes
  python3 tools/gen_kana_font.py --show あ print a glyph as text

Needs Pillow at the version tools/requirements-course.txt pins; the font is
fetched and checked by mkcourse.font_path(). tests/mkcourse_test.py runs the
--check.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mkcourse  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "firmware/main/lv_font_kana_20.c"
SIZE = 20
THRESHOLD = 72
RANGES = [(0x3001, 0x3002), (0x3041, 0x3096), (0x309B, 0x309E), (0x30A1, 0x30FA), (0x30FB, 0x30FE)]


def glyphs(font_path):
    from PIL import Image, ImageDraw, ImageFont
    f = ImageFont.truetype(str(font_path), SIZE, layout_engine=ImageFont.Layout.BASIC)
    out = []
    pad = SIZE * 2
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            ch = chr(cp)
            img = Image.new("L", (SIZE * 4, SIZE * 4), 0)
            ImageDraw.Draw(img).text((pad, pad), ch, fill=255, font=f, anchor="ls")
            bw = img.point(lambda v: 1 if v >= THRESHOLD else 0, mode="1")
            box = bw.getbbox()
            adv = int(round(f.getlength(ch) * 16))
            if not box:
                out.append((cp, adv, 0, 0, 0, 0, []))
                continue
            x0, y0, x1, y1 = box
            px = bw.load()
            rows = [[1 if px[x, y] else 0 for x in range(x0, x1)] for y in range(y0, y1)]
            # LVGL: ofs_x from the pen, ofs_y from the baseline up to the box's bottom
            out.append((cp, adv, x1 - x0, y1 - y0, x0 - pad, pad - y1, rows))
    return out


def pack(rows):
    bits = [b for r in rows for b in r]
    b = bytearray((len(bits) + 7) // 8)
    for i, v in enumerate(bits):
        if v:
            b[i // 8] |= 0x80 >> (i % 8)
    return bytes(b)


def build(font_path):
    gl = glyphs(font_path)
    top = max(g[5] + g[3] for g in gl if g[3])          # ink above the baseline
    bottom = max(-g[5] for g in gl if g[3])             # and below it
    line_h, base = top + bottom + 1, bottom
    bm = bytearray()
    dsc = ["{.bitmap_index=0,.adv_w=0,.box_w=0,.box_h=0,.ofs_x=0,.ofs_y=0},  /* id 0: none */"]
    for cp, adv, w, h, ox, oy, rows in gl:
        dsc.append("{.bitmap_index=%d,.adv_w=%d,.box_w=%d,.box_h=%d,.ofs_x=%d,.ofs_y=%d},  /* U+%04X */"
                   % (len(bm), adv, w, h, ox, oy, cp))
        bm += pack(rows)
    cmaps, gid = [], 1
    for lo, hi in RANGES:
        n = hi - lo + 1
        cmaps.append("{.range_start=%d,.range_length=%d,.glyph_id_start=%d,.unicode_list=NULL,"
                     ".glyph_id_ofs_list=NULL,.list_length=0,.type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}"
                     % (lo, n, gid))
        gid += n
    L = ['#include "lvgl.h"',
         '#include "lv_font_palm.h"',
         "",
         "/* Generated by tools/gen_kana_font.py: kana at %d px (line %d), 1bpp, from" % (SIZE, line_h),
         " * %s (sha256 %s...), the course pictures' font, at threshold %d." % (mkcourse.FONT_NAME, mkcourse.FONT_SHA256[:16], THRESHOLD),
         " * Don't edit; run the script. */",
         "",
         "static const uint8_t glyph_bitmap[] = {"]
    for i in range(0, len(bm), 32):
        L.append(",".join("0x%02x" % b for b in bm[i:i + 32]) + ",")
    L += ["};", "", "static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {"] + dsc + ["};", "",
          "static const lv_font_fmt_txt_cmap_t cmaps[] = {"]
    L += [c + "," for c in cmaps]
    L += ["};", "",
          "static const lv_font_fmt_txt_dsc_t font_dsc = {",
          ".glyph_bitmap=glyph_bitmap,.glyph_dsc=glyph_dsc,.cmaps=cmaps,.kern_dsc=NULL,",
          ".kern_scale=0,.cmap_num=%d,.bpp=1,.kern_classes=0,.bitmap_format=0};" % len(cmaps), "",
          "/* anything that isn't kana (a Latin reading, a hyphen) is drawn by the Palm font */",
          "const lv_font_t lv_font_kana_20 = {",
          ".get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,",
          ".line_height=%d,.base_line=%d,.subpx=LV_FONT_SUBPX_NONE," % (line_h, base),
          ".underline_position=-2,.underline_thickness=1,.dsc=&font_dsc,.fallback=&lv_font_palm};", ""]
    return "\n".join(L), len(bm), line_h


def main():
    fp = mkcourse.font_path(None)
    if len(sys.argv) >= 3 and sys.argv[1] == "--show":
        for cp, adv, w, h, ox, oy, rows in glyphs(fp):
            if cp == ord(sys.argv[2][0]):
                print("adv %.2f box %dx%d ofs %d,%d" % (adv / 16, w, h, ox, oy))
                for r in rows:
                    print("".join("#" if b else "." for b in r))
        return 0
    text, n, lh = build(fp)
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        if not OUT.exists() or OUT.read_text() != text:
            print("gen_kana_font: %s is stale; run tools/gen_kana_font.py" % OUT.relative_to(ROOT))
            return 1
        print("gen_kana_font: %s is current (%d B of bitmap, line %d px)" % (OUT.relative_to(ROOT), n, lh))
        return 0
    OUT.write_text(text)
    print("wrote %s (%d B of bitmap, line %d px)" % (OUT.relative_to(ROOT), n, lh))
    return 0


if __name__ == "__main__":
    sys.exit(main())
