#!/usr/bin/env python3
"""Emit the speaker portraits as LVGL A8 image descriptors for palm_icons.c.

A screen that has something to say stands a portrait in the right-hand margin
and hangs the words off it in a speech bubble -- the Coach's weekly report
("Week" on his home screen) is the one that exists today, and the Assistant and
the Guru are here for the screens that come after it. FACES below holds the
three reduced to 60 wide, which is what the margin right of the 164 px stat
column leaves on a 240 px screen.

Each began as a reduction of its source artwork -- binarise at 50%% grey, crop
to the framing, box-filter down against an ink-coverage threshold -- and each
was then finished by hand. **The text below is the artwork.** Nothing here is
re-derivable from a source image any more: re-running the reduction would throw
away a drawn neck and shoulders, a rebuilt lens rim, a mirrored eye. The source
files are not kept for that reason, and `--from-image` is for the *next*
portrait someone converts, not for these three. `--from-exact` is the door back
into the art below.

A8 (0 = transparent, 255 = ink) matches the launcher icons in palm_icons.c, so
ui.c recolors them to COL_LINE exactly the way it recolors those. They live in
flash as const rodata -- a few KB of a 3 MB app partition -- which is the whole
reason a portrait is an image and not a canvas: the 24 KB LVGL object pool
never sees it. See docs/BUILD_PROGRESS.md, "LVGL on a 24 KB object pool".

    python3 tools/gen_faces.py                   # all of them, for palm_icons.c
    python3 tools/gen_faces.py coach             # just the one
    python3 tools/gen_faces.py --preview NAME f.png [zoom]   # look at it (6x)
    python3 tools/gen_faces.py --from-exact NAME f.png       # take edits back
    python3 tools/gen_faces.py --from-image NAME src.png [W [ink [crop]]]

`--preview NAME f.png 1` and `--from-exact NAME` are a lossless round trip: the
art goes out as a black-on-white PNG at 1:1 or an integer zoom, comes back
pixel for pixel, and prints the new art on stderr to paste above and the new C
on stdout.

Two things worth knowing before converting a fourth portrait, both learned the
expensive way here. **Ink coverage is per-artwork**: solid-ink drawing reduces
at 128, but thin-outline drawing needs about 64, because at 15:1 a source line
covers roughly 7%% of a target pixel and 128 erases the outline outright,
leaving a hollow face. **The crop is the framing, not a margin trim**: cropping
to the ink bounding box puts a whole figure inside 60 px and leaves a head half
the size of one cropped to the shoulders, so pass a crop that frames the head
and lets the shoulders run off the sides.
"""
import sys

# beanie, headband, long hair, moustache. The neck and shoulders are drawn, not
# reduced: the source artwork stops at his chin, and he needs them to stand
# beside the other two. Hand-finished from there -- a neck generated to the
# Guru's proportions still sat wrong on him, because their chins are not at the
# same height. Hers is low with hair covering the jaw down to it, so barely two
# rows of neck ever show; his sits higher with nothing beside it, and the same
# pixels left the neck hanging in open white instead of attached under the chin.
COACH = """\
..........................#############.....................
......................#####################.................
......................######################................
....................##########################..............
..................##############################............
.................################################...........
................##################################..........
...............####################################.........
...............####################################.........
..............#######################################.......
..............#######################################.......
.............#########.............##################.......
.............######....................###############......
.............####.......................##############......
.............##............................###########......
............##.................................########.....
............#...................................#######.....
............#.....................................#####.....
...........##.....................................#####.....
...........#...........###########..................###.....
...........#......#####...........###................##.....
...........#...####..................##..............##.....
...........#..####.....................###............#.....
...........#######.......................###..........#.....
...........######.........................###.........#.....
...........###############........#######...###.......#.....
..........########.....####.....####....###.####......#.....
.........########.........................#######.....#.....
........########...########.....########....######...#......
.......########...#..###..#....##..###.##...#######..#......
#....##########...#..###...........###..##..##########......
###############.............................#########.......
.##############..............................#########......
..############...............................#########......
...###########...............................#########......
....##########...............................#########......
......########...............................#########......
...###########...............................##########.....
....##########...............................###########....
.......#######..........#.......#............############...
.......#######..........###...###...........################
.......#######.............###..............##############..
......########..............................##############..
......########......########.#####..........################
.....#########.....##################.......###############.
.....#########....#########...########.....#############....
.....##########...####.............####....#############....
....###########........###########...##....##############...
....###########............................##############...
....############..........####............################..
...#############..........................################..
...#############.........................#################..
...##############.......................##################..
..################......................##################..
..################....................####################..
...#############.##..................#####################..
...#############..##................##..#################...
....###########...##...............##...#################...
.....#########....#.#.............##....################....
......#######.....#..###......####......###############.....
........####......#...##########........##############......
.................#......................############........
...............##......................###########..........
.............##........................#########............
............###........................#######.###..........
..........##..#..........................#####.#..##........
........##....#................................#....##......\
"""

# bun, glasses, blazer. Everything outboard of each lens is redrawn. Four
# features -- ear, inner curl, hair strand and the lens's own outer rim -- fall
# inside eight columns, and the filter welded them: the rim disappeared into the
# hair strand entirely, leaving the lens with no outer edge and a black slab
# standing where it should have been. The rim is restored one column inboard of
# where the source puts it, which is what buys the white gap that keeps the
# strand, the ear and the glasses three separate things at 60 px. The ear closes
# onto the strand at the top and onto the jaw at the lobe, so it is attached at
# both ends. Her neck and collar are the only ones nothing was drawn into -- the
# crop takes them whole from the source. Hand-finished from there: the bun reads
# as a wrapped coil rather than a solid blob, and the temple arms carry across to
# the ears instead of stopping at the lens.
ASSISTANT = """\
............................................................
..........................########..........................
.......................#########..###.......................
.....................#############.####.....................
....................###############.#####...................
..................##################.#####..................
..................##################.#####..................
.................###################.######.................
.................###################.######.................
................###################.########................
................##################.#########................
................########.............#######................
.................####...#############..#####................
.................##..##################.###.................
................########################.###................
..............##########################.#####..............
.............###########################.######.............
............############################.#######............
............############################.########...........
...........############################.#########...........
..........#############################.##########..........
..........############################.###########..........
.........##########......................##########.........
.........#########........................#########.........
.........########..........................#########........
........########............................########........
........#######..............................#######........
........######...............................#######........
........######................................######........
........######................................######........
........#####..................................#####........
........#####....#######...........########....#####........
........#####..###.....##.........###.....###..#####........
........#####..................................#####........
........#####.############........############.#####........
........###################.....####################........
..........#####..######...##....##...######..#####..........
........####..#.########..##....##..########.#..####........
.......#..##..###.###.###.########.#####.#.###..##..#.......
.......#..##..#.#.#####...########.#.#####.#.#..##..#.......
......#.#.##..#...#####...###..###...#####...#..##.#.#......
......#.#.##..#..#####....##....##....#####..#..##.#.#......
......#.#.##..#...........##....##...........#..##.#.#......
......#.#.##..#...........##....##...........#..##.#.#......
......#.#.##..#...........##....##...........#..##.#.#......
.......#..##..#..........##.#....##..........#..##..#.......
.......#...#..#############.#....#############..#...#.......
........#..#...##########..#.......##########...#...#.......
........#..#..............#.....................#..#........
.........#..#.............#.....................#.#.........
..........###..............######..............###..........
............#..................................#............
.............#................................#.............
.............#................................#.............
.............#......................#.........#.............
.............##........##.........##.........##.............
..............#.........###########..........#..............
..............##............................##..............
...............#............................#...............
...............##...........####...........##...............
................##........................##................
.................##......................##.................
..................##....................##..................
...................##..................##...................
...................###................###...................
..................##.###............##..##..................
.................###...##.........###...###.................
................##.#.....##.....###.....####................
................#.##.......######.......##.#................
................#..##..................##..#................
...............#....##................##....#...............
...............#.....##..............##.....#...............
...............#......##............##......#...............
..............##........##.........#........##..............
.............###......##.#........#.###.....###.............
...........#####....##...##.......##..##....#####...........
........#######....##.....#......#.....##...########........\
"""

# bob, third eye, a knowing half-smile. Her left eye reduced a row taller than
# her right and ran into the bridge of the nose as one blob, so the right eye
# is mirrored across the face's axis -- the third eye and the mouth both centre
# on it. The nose came down as a stroke from brow to nostril, long and off that
# axis enough to read as a scar, and is shortened onto it. Her pearls are light
# grey in the source and reduced to nothing; they are drawn back on the arc they
# actually hang in, every other pixel, because a solid arc reads as a neckline
# rather than as beads. Her neck and shoulders are drawn too -- the source has
# them, but as thin verticals they fell through the filter into dots.
#
# Her artwork is where the neck idiom the other two follow was measured from,
# with the target pixel grid laid over it: vertical sides, a sharp corner, and a
# shoulder falling ten columns over six rows that leaves through the *bottom* of
# the frame. Splayed sides and near-flat shoulders to the edges read as a yoke
# rather than a body. Copy the idiom, not the pixels -- see the Coach.
GURU = """\
......................##############........................
....................##################......................
..................######################....................
................##########################..................
...............#############################................
.............#################################..............
............###################################.............
...........#####################################............
..........#######################################...........
.........#########################################..........
........###########################################.........
.......#############################################........
......###############################################.......
......###############################################.......
......###############################################.......
.....###############...###############################......
.....##############.....##############################......
....#############...........###########################.....
....############.................######################.....
....############.....................##################.....
....###########.........................###############.....
....###########...........................##############....
....###########............#####...........#############....
...###########...........##.##.##...........############....
...##########.............#.##.#............############....
...##########..............####.............#############...
..###########................................############...
..###########................................############...
..###########..##########.........##########..############..
..###########..##########........###########..############..
..##########..................................############..
.###########...................................###########..
.###########......#######..........#######.....###########..
.###########.....#########........#########....###########..
.###########....##.###.#.#........#.###.#.##...############.
############....##.#####.#........#.#####.##...############.
############........####............####.......############.
############................#..................############.
############................#..................############.
############................#..................#############
############................#..................#############
############...................................#############
############...................................#############
############...................................#############
#############..................................#############
#############............###...###............##############
#############..............#####..............##############
#############.................................##############
#############................................###############
.#############...............................##############.
..############...............................#############..
...###########..............................#############...
....##########........##...........##.......############....
.....##########.........###########.........###########.....
......#########............................###########......
.......#########...........####............##########.......
........########..........................##########........
.........########........................##########.........
..........########......................##########..........
...........########....................##########...........
............#########.................##########............
.............######.##...............##.######..............
..............#####..##............##...#####...............
...............####...###.........##....####................
................###.....##########......###.................
.................##.......#######.......##..................
..................#......................#..................
..................##...................#.#..................
................##...#...............#....##................
..............##.......#...........#........##..............
.............#...........#.......#............#.............
...........##..............#.#.#...............##...........
.........##......................................##.........
........#..........................................#........\
"""

# name -> (art, C symbol, what the descriptor is for)
FACES = {
    "coach":     (COACH, "coach_face", "Coach's portrait for the weekly report"),
    "assistant": (ASSISTANT, "assistant_face", "the Assistant's portrait"),
    "guru":      (GURU, "guru_face", "the Guru's portrait"),
}


def art(name):
    """the checked-in text as (grid, w, h), with the rows checked square"""
    grid = FACES[name][0].strip().split("\n")
    w = len(grid[0])
    assert all(len(r) == w for r in grid), "%s rows are not all one width" % name
    return grid, w, len(grid)


GRID, W, H = art("coach")


def emit_c(name, grid=None, w=None, h=None):
    if grid is None:
        grid, w, h = art(name)
    sym, what = FACES[name][1], FACES[name][2]
    data = ",".join("255" if ch == "#" else "0" for row in grid for ch in row)
    print("/* %s -- tools/gen_faces.py */" % what)
    print("static const uint8_t %s_map[] = {%s};" % (sym, data))
    print("const lv_image_dsc_t %s = {" % sym)
    print("  .header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_A8,.flags=0,"
          ".w=%d,.h=%d,.stride=%d,.reserved_2=0}," % (w, h, w))
    print("  .data_size=%d,.data=%s_map };" % (w * h, sym))


def emit_png(path, grid=GRID, w=W, h=H, scale=6):
    """stdlib PNG, the same way sim/tools/ppm2png.py does it"""
    import struct, zlib
    rows = b""
    for y in range(h):
        line = b"\x00"
        for x in range(w):
            line += (b"\x00" if grid[y][x] == "#" else b"\xff") * scale
        rows += line * scale
    def chunk(tag, data):
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c))
    open(path, "wb").write(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", w * scale, h * scale, 8, 0, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(rows))
        + chunk(b"IEND", b""))
    print("wrote %s (%dx%d)" % (path, w * scale, h * scale), file=sys.stderr)


def from_image(path, w=60, thresh=128, box=None):
    """Reduce source artwork to art text. For NEW portraits, not for these three.

    Every face above was finished by hand after its own reduction, so running
    this at one of them would discard that work -- the text above is the
    artwork. This is the importer for the next one.

    `thresh` is ink coverage per target pixel, 0..255; `box` is a source-pixel
    crop, and it is the framing rather than a margin trim. See the module
    docstring for why both of those matter more than they look like they do.
    Height follows the crop's aspect.
    """
    from PIL import Image                      # only this path needs Pillow
    im = Image.open(path).convert("L")
    ink = im.point(lambda v: 255 if v < 128 else 0)
    ink = ink.crop(box or ink.getbbox())
    h = int(round(w * ink.size[1] / float(ink.size[0])))
    cov = ink.resize((w, h), Image.BOX).load() # per-target-pixel ink coverage
    grid = ["".join("#" if cov[x, y] >= thresh else "." for x in range(w))
            for y in range(h)]
    return grid, w, h


def read_png(path):
    """Minimal stdlib PNG reader -> (pixels, w, h) with pixels[y][x] = 1 for ink.

    Enough of the format to swallow whatever a pixel editor saves: 8/16-bit
    grey, RGB, RGBA and palette, with or without alpha. Ink is "dark and not
    transparent", so a white or empty background reads as paper either way.
    Interlaced files are refused rather than silently misread.
    """
    import struct, zlib
    raw = open(path, "rb").read()
    if raw[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit("%s is not a PNG" % path)
    pos, idat, plte, trns = 8, b"", None, None
    while pos < len(raw):
        (ln,) = struct.unpack(">I", raw[pos:pos + 4])
        tag = raw[pos + 4:pos + 8]
        body = raw[pos + 8:pos + 8 + ln]
        pos += 12 + ln
        if   tag == b"IHDR": w, h, depth, ctype, _, _, ilace = struct.unpack(">IIBBBBB", body)
        elif tag == b"PLTE": plte = body
        elif tag == b"tRNS": trns = body
        elif tag == b"IDAT": idat += body
        elif tag == b"IEND": break
    if ilace:
        raise SystemExit("%s is interlaced; re-save it without Adam7" % path)
    nch = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype]
    bpp = max(1, nch * depth // 8)                 # filter distance, in bytes
    stride = (w * nch * depth + 7) // 8
    data = zlib.decompress(idat)
    out, prev = [], bytearray(stride)
    for y in range(h):                             # undo the per-row filters
        f = data[y * (stride + 1)]
        row = bytearray(data[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
        for i in range(stride):
            a = row[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if   f == 1: row[i] = (row[i] + a) & 255
            elif f == 2: row[i] = (row[i] + b) & 255
            elif f == 3: row[i] = (row[i] + (a + b) // 2) & 255
            elif f == 4:
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                row[i] = (row[i] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 255
        out.append(bytes(row)); prev = row

    def samples(row):                              # unpack to 0..255 per channel
        if depth == 8:  return list(row)
        if depth == 16: return [row[i] for i in range(0, len(row), 2)]
        per, mask, mx = 8 // depth, (1 << depth) - 1, (1 << depth) - 1
        vals = []
        for byte in row:
            for k in range(per):
                vals.append((byte >> (8 - depth * (k + 1))) & mask)
        return [v if ctype == 3 else v * 255 // mx for v in vals]

    px = []
    for row in out:
        v, line = samples(row), []
        for x in range(w):
            s = v[x * nch:(x + 1) * nch]
            if ctype == 3:
                i = s[0]
                lum = (plte[i * 3] * 299 + plte[i * 3 + 1] * 587 + plte[i * 3 + 2] * 114) // 1000
                alpha = trns[i] if trns and i < len(trns) else 255
            elif ctype in (2, 6):
                lum = (s[0] * 299 + s[1] * 587 + s[2] * 114) // 1000
                alpha = s[3] if ctype == 6 else 255
            else:
                lum, alpha = s[0], (s[1] if ctype == 4 else 255)
            line.append(1 if (alpha >= 128 and lum < 128) else 0)
        px.append(line)
    return px, w, h


def from_exact(name, path):
    """Read back an edited PNG pixel-for-pixel -- no crop, no rescale.

    This is the other half of `--preview`: hand someone the art at 1:1 or at an
    integer zoom, let them push individual pixels, and take it back unchanged.
    Unlike --from-image there is no ink-bbox crop and no box filter, so a stray
    edit at the edge shifts nothing else. At a zoom of k each k*k block votes,
    which absorbs an editor that antialiased a brush stroke.
    """
    _, w, h = art(name)
    px, pw, ph = read_png(path)
    if pw % w or ph % h or pw // w != ph // h:
        raise SystemExit("%s is %dx%d; expected %dx%d or an integer zoom of it"
                         % (path, pw, ph, w, h))
    k = pw // w
    grid = []
    for y in range(h):
        row = ""
        for x in range(w):
            ink = sum(px[y * k + b][x * k + a] for b in range(k) for a in range(k))
            row += "#" if ink * 2 >= k * k else "."
        grid.append(row)
    return grid, w, h


def need(name):
    if name not in FACES:
        raise SystemExit("no such face %r; have %s"
                         % (name, ", ".join(sorted(FACES))))
    return name


def redraw(name, grid, w, h):
    """print the new art on stderr to paste back, and the new C on stdout"""
    print('%s = """\\' % name.upper(), file=sys.stderr)
    print("\n".join(grid), file=sys.stderr)
    print('"""', file=sys.stderr)
    emit_c(name, grid, w, h)


if __name__ == "__main__":
    a = sys.argv[1:]
    if len(a) > 2 and a[0] == "--from-exact":
        redraw(need(a[1]), *from_exact(a[1], a[2]))
    elif len(a) > 2 and a[0] == "--from-image":
        box = tuple(int(v) for v in a[5].split(",")) if len(a) > 5 else None
        redraw(need(a[1]), *from_image(a[2], int(a[3]) if len(a) > 3 else 60,
                                       int(a[4]) if len(a) > 4 else 128, box))
    elif len(a) > 2 and a[0] == "--preview":
        grid, w, h = art(need(a[1]))
        emit_png(a[2], grid, w, h, int(a[3]) if len(a) > 3 else 6)
    elif a and not a[0].startswith("-"):
        emit_c(need(a[0]))
    elif a:
        raise SystemExit("\n".join(l for l in __doc__.split("\n")
                                   if l.startswith("    python3")))
    else:
        for i, name in enumerate(FACES):
            if i:
                print()
            emit_c(name)
