#!/usr/bin/env python3
"""Emit the Coach portrait as an LVGL A8 image descriptor for palm_icons.c.

The weekly report ("Week" on Coach's home screen) stands the coach beside the
statistics and hangs his advice off him in a speech bubble. FACE below is the
supplied portrait -- beanie, headband, long hair, moustache -- reduced to the
60x65 that fits in the margin right of the 164 px stat column on a 240 px
screen. It was derived from the source artwork once, by binarising at 50%%
grey, cropping to the ink, and box-filtering down with a 50%% ink-coverage
threshold; `--from-image` below reruns exactly that recipe, so a new source or
a different target size is a one-liner rather than a redraw. The reduced art is
checked in as text because it is the thing that actually ships: it reviews as a
diff, and the normal path needs nothing but the standard library.

A8 (0 = transparent, 255 = ink) matches the launcher icons in palm_icons.c, so
ui.c recolors it to COL_LINE exactly the way it recolors those. It lives in
flash as const rodata -- 3900 bytes of a 3 MB app partition -- which is the
whole reason the portrait is an image and not a canvas: the 24 KB LVGL object
pool never sees it. See docs/BUILD_PROGRESS.md, "LVGL on a 24 KB object pool".

    python3 tools/gen_coach_face.py                  # the C, for palm_icons.c
    python3 tools/gen_coach_face.py --preview f.png  # look at it first (6x)
    python3 tools/gen_coach_face.py --from-image src.png [W H]   # needs Pillow
"""
import sys

FACE = """\
..........................#############.....................
......................#####################.................
......................######################................
....................##########################..............
..................##############################............
.................################################...........
................##################################..........
...............####################################.........
...............####################################.........
..............#######################################.......
..............#######################################.......
.............#########.............##################.......
.............######....................###############......
.............####.......................##############......
.............##............................###########......
............##.................................########.....
............#...................................#######.....
............#.....................................#####.....
...........##.....................................#####.....
...........#........................................###.....
...........#......#####.........#####................##.....
...........#...####................####..............##.....
...........#..####.....................###............#.....
...........#######.......................###..........#.....
...........######.........................###.........#.....
...........###############..................###.......#.....
..........########.....####.......#######...####......#.....
.........########.....###.........#########.#####.....#.....
........########...########......##.......########...#......
.......########...#.###.###.....########....#######..#......
#....##########...#..##........##..######...##########......
###############.....................###.##..#########.......
.##############.....................###.##...#########......
..############...............................#########......
...###########...............................#########......
....##########...............................#########......
......########...............................#########......
...###########...............................##########.....
....##########...............................###########....
.......#######..........#....................############...
.......#######..........###.....#...........################
.......#######.............######...........##############..
......########..........###.................##############..
......########......########.#####..........################
.....#########.....##################.......###############.
.....#########....###.#####...########.....#############....
.....##########...####.............####....#############....
....###########.............######...##....##############...
....###########............................##############...
....############..........................################..
...#############..........................################..
...#############.........................#################..
...##############.......................##################..
..################......................##################..
..################....................####################..
...#############.##..................###.#################..
...#############..##................##...################...
....###########....#...............##....################...
.....#########......#.............##.....###############....
......#######........###......####.......##############.....
........####..........##########........##############......
........................................############........
........................................##########..........
.......................................#########............
.......................................#######..............\
"""

GRID = [line for line in FACE.strip().split("\n")]
H = len(GRID)
W = len(GRID[0])
assert all(len(r) == W for r in GRID), "FACE rows are not all the same width"


def emit_c(grid=GRID, w=W, h=H):
    data = ",".join("255" if ch == "#" else "0" for row in grid for ch in row)
    print("/* Coach's portrait for the weekly report -- tools/gen_coach_face.py */")
    print("static const uint8_t coach_face_map[] = {%s};" % data)
    print("const lv_image_dsc_t coach_face = {")
    print("  .header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_A8,.flags=0,"
          ".w=%d,.h=%d,.stride=%d,.reserved_2=0}," % (w, h, w))
    print("  .data_size=%d,.data=coach_face_map };" % (w * h))


def emit_png(path, grid=GRID, w=W, h=H, scale=6):
    """stdlib PNG, the same way sim/tools/ppm2png.py does it"""
    import struct, zlib
    rows = b""
    for y in range(h):
        line = b"\x00"
        for x in range(w):
            line += (b"\x00" if grid[y][x] == "#" else b"\xff") * scale
        rows += line * scale
    def chunk(tag, data):
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c))
    open(path, "wb").write(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", w * scale, h * scale, 8, 0, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(rows))
        + chunk(b"IEND", b""))
    print("wrote %s (%dx%d)" % (path, w * scale, h * scale), file=sys.stderr)


def from_image(path, w=None, h=None):
    """re-derive FACE from source artwork; aspect is taken from the ink bbox"""
    from PIL import Image                      # only this path needs Pillow
    im = Image.open(path).convert("L")
    ink = im.point(lambda v: 255 if v < 128 else 0)
    ink = ink.crop(ink.getbbox())              # trim the paper margin
    if w is None:
        w = 60
    if h is None:
        h = int(round(w * ink.size[1] / float(ink.size[0])))
    cov = ink.resize((w, h), Image.BOX).load() # per-target-pixel ink coverage
    grid = ["".join("#" if cov[x, y] >= 128 else "." for x in range(w))
            for y in range(h)]
    return grid, w, h


if __name__ == "__main__":
    a = sys.argv[1:]
    if a and a[0] == "--from-image":
        size = (int(a[2]), int(a[3])) if len(a) > 3 else (None, None)
        grid, w, h = from_image(a[1], *size)
        print('FACE = """\\', file=sys.stderr)
        print("\n".join(grid), file=sys.stderr)
        print('"""', file=sys.stderr)
        emit_c(grid, w, h)
    elif len(a) > 1 and a[0] == "--preview":
        emit_png(a[1])
    else:
        emit_c()
