#!/usr/bin/env python3
"""Generate firmware/main/study_demo.c from courses/demo-kanji/course.srs.

The demo course ships inside the firmware (SRS_PLAN.md section 9), so a new
user can open Study and do real lessons before copying any course to the card.
The first time Study opens with a card in, it writes these bytes to
/sdcard/study/demo-kanji/course.srs.

    tools/gen_study_demo.py            # regenerate study_demo.c
    tools/gen_study_demo.py --check    # fail if it is out of date (CI)

The .srs is the source and the .c a build product, the way guru_pool.c is:
never hand-edit the .c. The course file itself is built by tools/mkcourse.py
and checked byte for byte in CI, so this only has to copy it faithfully -- and
it checks the copy is a course (magic, size, header CRC) before writing a byte.
"""
import argparse
import struct
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "courses" / "demo-kanji" / "course.srs"
OUT = ROOT / "firmware" / "main" / "study_demo.c"


def generate():
    data = SRC.read_bytes()
    if data[:4] != b"SRSC" or struct.unpack_from("<I", data, 8)[0] != len(data) \
            or zlib.crc32(data[:28]) & 0xFFFFFFFF != struct.unpack_from("<I", data, 28)[0]:
        sys.exit("gen_study_demo: %s is not a whole course file" % SRC)
    fp = struct.unpack_from("<I", data, 24)[0]
    lines = [
        "/* study_demo.c -- GENERATED by tools/gen_study_demo.py from",
        " * courses/demo-kanji/course.srs. Do not edit: change the course source,",
        " * rebuild it with tools/mkcourse.py, and regenerate this. */",
        '#include "study_demo.h"',
        "",
        "const uint32_t study_demo_size = %d;" % len(data),
        "const uint32_t study_demo_fingerprint = 0x%08x;" % fp,
        "const uint8_t study_demo_srs[%d] = {" % len(data),
    ]
    for i in range(0, len(data), 24):
        lines.append("  " + ",".join("%d" % b for b in data[i:i + 24]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if study_demo.c is out of date")
    a = ap.parse_args()
    text = generate()
    if a.check:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("gen_study_demo: firmware/main/study_demo.c is out of date; run tools/gen_study_demo.py")
        print("gen_study_demo: study_demo.c matches courses/demo-kanji/course.srs")
        return
    OUT.write_text(text)
    print("gen_study_demo: wrote %s (%d bytes of course)" % (OUT.relative_to(ROOT), len(SRC.read_bytes())))


if __name__ == "__main__":
    main()
