#!/usr/bin/env python3
"""Pixel-double an LVGL 1-bpp font: lv_font_palm_bold.c -> lv_font_palm_bold_2x.c.

The Palm bold font drawn at twice the size, each pixel a 2x2 block, so the
big text on Study's answers is the same face as the rest of the UI (not a
smoothed outline font at 30 px). The glyph metrics double with it. It is all
const: flash only, no RAM.

  python3 tools/gen_font_2x.py           write firmware/main/lv_font_palm_bold_2x.c
  python3 tools/gen_font_2x.py --check   exit 1 if the file isn't what this writes
  python3 tools/gen_font_2x.py --show A  print a glyph of both fonts as text
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "firmware/main/lv_font_palm_bold.c"
OUT = ROOT / "firmware/main/lv_font_palm_bold_2x.c"
DSC_KEYS = ("bitmap_index", "adv_w", "box_w", "box_h", "ofs_x", "ofs_y")


def parse(text):
    bm = re.search(r"glyph_bitmap\[\]\s*=\s*\{(.*?)\};", text, re.S).group(1)
    bitmap = bytes(int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]+", bm))
    dsc_txt = re.search(r"glyph_dsc\[\]\s*=\s*\{(.*?)\n\};", text, re.S).group(1)
    dsc = []
    for m in re.finditer(r"\{([^{}]*)\}", dsc_txt):
        d = dict((k, int(v)) for k, v in re.findall(r"\.(\w+)=(-?\d+)", m.group(1)))
        dsc.append(tuple(d[k] for k in DSC_KEYS))
    cmaps = re.search(r"(static const lv_font_fmt_txt_cmap_t cmaps\[\] = \{.*?\};)", text, re.S).group(1)
    lh = int(re.search(r"\.line_height=(\d+)", text).group(1))
    bl = int(re.search(r"\.base_line=(\d+)", text).group(1))
    return bitmap, dsc, cmaps, lh, bl


def rows(bitmap, d):
    """The glyph's pixels, row by row: the bits run on without row padding."""
    idx, _, w, h, _, _ = d
    out = []
    for y in range(h):
        row = []
        for x in range(w):
            bit = y * w + x
            row.append((bitmap[idx + bit // 8] >> (7 - bit % 8)) & 1)
        out.append(row)
    return out


def pack(pix):
    bits = [b for row in pix for b in row]
    out = bytearray((len(bits) + 7) // 8)
    for i, b in enumerate(bits):
        if b:
            out[i // 8] |= 0x80 >> (i % 8)
    return bytes(out)


def build():
    bitmap, dsc, cmaps, lh, bl = parse(SRC.read_text())
    out_bm = bytearray()
    out_dsc = []
    for d in dsc:
        idx, adv, w, h, ox, oy = d
        pix = rows(bitmap, d)
        big = []
        for r in pix:
            wide = [b for b in r for _ in (0, 1)]
            big += [wide, list(wide)]
        start = len(out_bm)
        out_bm += pack(big)
        out_dsc.append((start, adv * 2, w * 2, h * 2, ox * 2, oy * 2))
    lines = ['#include "lvgl.h"', "",
             "/* Generated by tools/gen_font_2x.py from lv_font_palm_bold.c: the Palm",
             " * bold font pixel-doubled, 1bpp, %dpx. Don't edit; run the script. */" % (lh * 2), "",
             "static const uint8_t glyph_bitmap[] = {"]
    for i in range(0, len(out_bm), 32):
        lines.append(",".join("0x%02x" % b for b in out_bm[i:i + 32]) + ",")
    lines += ["};", "", "static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {"]
    for d in out_dsc:
        lines.append("{" + ",".join(".%s=%d" % kv for kv in zip(DSC_KEYS, d)) + "},")
    lines += ["};", "", cmaps, "",
              "static const lv_font_fmt_txt_dsc_t font_dsc = {",
              ".glyph_bitmap=glyph_bitmap,.glyph_dsc=glyph_dsc,.cmaps=cmaps,.kern_dsc=NULL,",
              ".kern_scale=0,.cmap_num=1,.bpp=1,.kern_classes=0,.bitmap_format=0};", "",
              "const lv_font_t lv_font_palm_bold_2x = {",
              ".get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,",
              ".line_height=%d,.base_line=%d,.subpx=LV_FONT_SUBPX_NONE," % (lh * 2, bl * 2),
              ".underline_position=-2,.underline_thickness=2,.dsc=&font_dsc};", ""]
    return "\n".join(lines), len(out_bm)


def main():
    if len(sys.argv) >= 3 and sys.argv[1] == "--show":
        ch = ord(sys.argv[2][0])
        bitmap, dsc, _, _, _ = parse(SRC.read_text())
        for r in rows(bitmap, dsc[ch - 32 + 1]):
            print("".join("#" if b else "." for b in r))
        print()
        text, _ = build()
        bitmap, dsc, _, _, _ = parse(text)
        for r in rows(bitmap, dsc[ch - 32 + 1]):
            print("".join("#" if b else "." for b in r))
        return 0
    text, n = build()
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        if not OUT.exists() or OUT.read_text() != text:
            print("gen_font_2x: %s is stale; run tools/gen_font_2x.py" % OUT.relative_to(ROOT))
            return 1
        print("gen_font_2x: %s is current (%d B of bitmap)" % (OUT.relative_to(ROOT), n))
        return 0
    OUT.write_text(text)
    print("wrote %s (%d B of bitmap)" % (OUT.relative_to(ROOT), n))
    return 0


if __name__ == "__main__":
    sys.exit(main())
